global:
  external_labels:
    monitor: 'swarm'

scrape_configs:
  - job_name: consul
    consul_sd_configs:
      - server: 172.17.0.1:8500
    relabel_configs:
      - source_labels: ["__meta_consul_tags"]
        regex: .*,prometheus,.*
        action: keep
      - source_labels: ["__meta_consul_service"]
        target_label: job

